
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.cunoc.Instructor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 21;
  public static final int PUNTO = 24;
  public static final int INSERTAR = 14;
  public static final int OR = 22;
  public static final int IGUAL = 7;
  public static final int MENORIGUAL = 3;
  public static final int DECIMAL = 28;
  public static final int ELIMINAR = 15;
  public static final int ID_ARCHIVO = 27;
  public static final int MAYORQUE = 6;
  public static final int ID = 25;
  public static final int FILTRAR = 18;
  public static final int OTRO = 26;
  public static final int VALORES = 20;
  public static final int ASIGNAR = 17;
  public static final int ACTUALIZAR = 16;
  public static final int COMA = 10;
  public static final int ASTERISCO = 23;
  public static final int DISTINTO = 2;
  public static final int EOF = 0;
  public static final int PAR_CLO = 12;
  public static final int MENORQUE = 5;
  public static final int COMILLA = 8;
  public static final int MAYORIGUAL = 4;
  public static final int error = 1;
  public static final int PAR_OP = 11;
  public static final int PC = 9;
  public static final int EN = 19;
  public static final int ENTERO = 29;
  public static final int SELECCIONAR = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISTINTO",
  "MENORIGUAL",
  "MAYORIGUAL",
  "MENORQUE",
  "MAYORQUE",
  "IGUAL",
  "COMILLA",
  "PC",
  "COMA",
  "PAR_OP",
  "PAR_CLO",
  "SELECCIONAR",
  "INSERTAR",
  "ELIMINAR",
  "ACTUALIZAR",
  "ASIGNAR",
  "FILTRAR",
  "EN",
  "VALORES",
  "AND",
  "OR",
  "ASTERISCO",
  "PUNTO",
  "ID",
  "OTRO",
  "ID_ARCHIVO",
  "DECIMAL",
  "ENTERO"
  };
}

