
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.cunoc.Proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOSQUE = 3;
  public static final int CARPETA = 10;
  public static final int ARCHIVO = 9;
  public static final int PROYECTO = 8;
  public static final int EOF = 0;
  public static final int MAYORQUE = 4;
  public static final int DIRECCION = 13;
  public static final int DIAGONAL = 5;
  public static final int IGUAL = 2;
  public static final int error = 1;
  public static final int ID_ARCHIVO = 12;
  public static final int NOMBRE = 6;
  public static final int COMILLA = 11;
  public static final int UBICACION = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "MENOSQUE",
  "MAYORQUE",
  "DIAGONAL",
  "NOMBRE",
  "UBICACION",
  "PROYECTO",
  "ARCHIVO",
  "CARPETA",
  "COMILLA",
  "ID_ARCHIVO",
  "DIRECCION"
  };
}

